services:
  - type: web
    name: hereyes
    runtime: docker
    repo: https://github.com/shubhyagami/streaming
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SERVER_PORT
        value: 8085
      - key: RAPIDAPI_KEY
        value: e9f2c625ebmsh6cd2de7109f2f5ep1f9991jsn4f3b636412b2
