services:
  - type: web
    name: hereyes
    env: docker
    repo: https://github.com/shubhyagami/streaming
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SERVER_PORT
        value: 8085
      - key: RAPIDAPI_KEY
        sync: false
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:./data/poweramp;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=TRUE
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
