server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: poweramp-spring
  datasource:
    url: jdbc:h2:mem:poweramp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8

poweramp:
  library:
    base-path: /music
  audio:
    temp-output: /tmp/poweramp-output
  songs-dir: /tmp/poweramp-songs
  rapidapi:
    host: youtube138.p.rapidapi.com
    download-host: youtube-mp3-audio-video-downloader.p.rapidapi.com
    spotify-host: spotify81.p.rapidapi.com
    key: ${RAPIDAPI_KEY:e9f2c625ebmsh6cd2de7109f2f5ep1f9991jsn4f3b636412b2}
  defaults:
    sample-rate: 44100
    bit-depth: 16
    channels: 2

logging:
  level:
    com.poweramp: INFO
    org.springframework: WARN
